# Stage-2 T4: full synthesis + implementation of trace_probe_top with real
# board pins and clock constraints, on xc7a35tfgg484-2.
#
# Goal: post-implementation utilization + timing slack — the authoritative
# answer to "does the trace probe fit on 35T?" Combines T1 (Ethernet),
# T2 (capture front-end), T3 (trace core) under one top.

set part xc7a35tfgg484-2
set syn_dir   [file dirname [info script]]
set repo_root [file normalize [file join $syn_dir .. ..]]
set veth      $repo_root/syn/external/verilog-ethernet
set ex        $veth/example/NexysVideo/fpga

# --- T2 capture front-end ---
read_verilog $syn_dir/rtl/trace_capture_a7.v
# --- T3 traceIF (hand-written Verilog) ---
read_verilog $repo_root/verilog/traceIF.v
# --- T3 Amaranth-derived modules (regenerated by export_trace_modules.py) ---
foreach m {tpiu_demux checksum_appender cobs_encoder super_framer} {
    read_verilog $syn_dir/$m.v
}
# --- T1 Ethernet stack (NexysVideo example) ---
foreach s {
    rtl/fpga_core.v
    rtl/debounce_switch.v
    rtl/sync_signal.v
    lib/eth/rtl/iddr.v
    lib/eth/rtl/oddr.v
    lib/eth/rtl/ssio_ddr_in.v
    lib/eth/rtl/ssio_ddr_out.v
    lib/eth/rtl/rgmii_phy_if.v
    lib/eth/rtl/eth_mac_1g_rgmii_fifo.v
    lib/eth/rtl/eth_mac_1g_rgmii.v
    lib/eth/rtl/eth_mac_1g.v
    lib/eth/rtl/axis_gmii_rx.v
    lib/eth/rtl/axis_gmii_tx.v
    lib/eth/rtl/lfsr.v
    lib/eth/rtl/eth_axis_rx.v
    lib/eth/rtl/eth_axis_tx.v
    lib/eth/rtl/udp_complete.v
    lib/eth/rtl/udp_checksum_gen.v
    lib/eth/rtl/udp.v
    lib/eth/rtl/udp_ip_rx.v
    lib/eth/rtl/udp_ip_tx.v
    lib/eth/rtl/ip_complete.v
    lib/eth/rtl/ip.v
    lib/eth/rtl/ip_eth_rx.v
    lib/eth/rtl/ip_eth_tx.v
    lib/eth/rtl/ip_arb_mux.v
    lib/eth/rtl/arp.v
    lib/eth/rtl/arp_cache.v
    lib/eth/rtl/arp_eth_rx.v
    lib/eth/rtl/arp_eth_tx.v
    lib/eth/rtl/eth_arb_mux.v
    lib/eth/lib/axis/rtl/arbiter.v
    lib/eth/lib/axis/rtl/priority_encoder.v
    lib/eth/lib/axis/rtl/axis_fifo.v
    lib/eth/lib/axis/rtl/axis_async_fifo.v
    lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
    lib/eth/lib/axis/rtl/sync_reset.v
} {
    read_verilog $ex/$s
}

# --- top + xdc ---
read_verilog $syn_dir/rtl/trace_probe_top.v
read_xdc     $syn_dir/constraints/trace_probe.xdc

synth_design -top trace_probe_top -part $part
puts "============ POST-SYNTH UTILIZATION ============"
report_utilization

opt_design
place_design
route_design

puts "============ POST-IMPLEMENTATION UTILIZATION ============"
report_utilization
puts "============ POST-IMPLEMENTATION TIMING ============"
report_timing_summary -no_detailed_paths -no_header

# r09 B1: dump worst-case slack for both setup and hold across all corners
# so the WNS/WHS numbers in the report are no longer ambiguous.
puts "============ WORST CASE SETUP / HOLD ============"
puts "--- worst SETUP path ---"
report_timing -delay_type max -max_paths 1 -path_type summary
puts "--- worst HOLD path ---"
report_timing -delay_type min -max_paths 1 -path_type summary
puts "--- IDDR-related hold paths (top 5) ---"
report_timing -delay_type min -max_paths 5 -path_type summary -through [get_pins -hierarchical -filter "REF_NAME == IDDR"]

# r09 A1: prove trace pipeline survives opt_design pruning.
puts "============ TRACE PIPELINE SURVIVAL CHECK ============"
foreach inst {u_capture u_traceif u_dmux u_chk u_cobs u_sf} {
    # Vivado >=2020.2: get_cells * inside the hierarchical instance.
    # Use an absolute hierarchical wildcard with leading slash semantics.
    set cells [get_cells -quiet -hierarchical -filter "NAME =~ $inst/*"]
    if {[llength $cells] == 0} {
        # try direct child (for non-flattened or DONT_TOUCH-protected blackbox)
        set self [get_cells -quiet $inst]
        if {[llength $self] > 0} {
            set cells [get_cells -quiet -filter "PARENT == $inst"]
            if {[llength $cells] == 0} {
                # if it's a leaf (DONT_TOUCH boxed), at least the box itself is there
                set cells $self
            }
        }
    }
    set lut [llength [filter $cells "REF_NAME =~ LUT*"]]
    set ff  [llength [filter $cells "REF_NAME =~ FD*"]]
    set ram [llength [filter $cells "REF_NAME =~ RAMB*"]]
    set io  [llength [filter $cells "REF_NAME =~ IDDR* || REF_NAME =~ IDELAY*"]]
    puts [format "  %-12s : LUT=%4d FF=%4d BRAM=%2d IO=%2d  (%d total cells)" \
                 $inst $lut $ff $ram $io [llength $cells]]
}

puts "============ TRACE PIPELINE TOP-LEVEL SIGNAL CHECK ============"
foreach sig {fr_avail frame128 fr_pulse dmux_out_valid chk_out_valid cobs_out_valid sf_out_valid} {
    set nets [get_nets -hierarchical -top_net_of_hierarchical_group "trace_probe_top/$sig"]
    if {[llength $nets] > 0} {
        puts "  net trace_probe_top/$sig : SURVIVED"
    } else {
        # try simple non-hierarchical
        set net [get_nets -quiet $sig]
        if {[llength $net] > 0} {
            puts "  net $sig : SURVIVED (top-level)"
        } else {
            puts "  net $sig : *** OPTIMIZED AWAY ***"
        }
    }
}
