# Stage-2 T4: full synthesis + implementation of trace_probe_top with real
# board pins and clock constraints, on xc7a35tfgg484-2.
#
# Goal: post-implementation utilization + timing slack — the authoritative
# answer to "does the trace probe fit on 35T?" Combines T1 (Ethernet),
# T2 (capture front-end), T3 (trace core) under one top.

set part xc7a35tfgg484-2
set syn_dir   [file dirname [info script]]
set repo_root [file normalize [file join $syn_dir .. ..]]
set veth      $repo_root/syn/external/verilog-ethernet
set ex        $veth/example/NexysVideo/fpga

# --- T2 capture front-end ---
read_verilog $syn_dir/rtl/trace_capture_a7.v
# --- T3 traceIF (hand-written Verilog) ---
read_verilog $repo_root/verilog/traceIF.v
# --- T3 Amaranth-derived modules (regenerated by export_trace_modules.py) ---
foreach m {tpiu_demux checksum_appender cobs_encoder super_framer} {
    read_verilog $syn_dir/$m.v
}
# --- T1 Ethernet stack (NexysVideo example) ---
foreach s {
    rtl/fpga_core.v
    rtl/debounce_switch.v
    rtl/sync_signal.v
    lib/eth/rtl/iddr.v
    lib/eth/rtl/oddr.v
    lib/eth/rtl/ssio_ddr_in.v
    lib/eth/rtl/ssio_ddr_out.v
    lib/eth/rtl/rgmii_phy_if.v
    lib/eth/rtl/eth_mac_1g_rgmii_fifo.v
    lib/eth/rtl/eth_mac_1g_rgmii.v
    lib/eth/rtl/eth_mac_1g.v
    lib/eth/rtl/axis_gmii_rx.v
    lib/eth/rtl/axis_gmii_tx.v
    lib/eth/rtl/lfsr.v
    lib/eth/rtl/eth_axis_rx.v
    lib/eth/rtl/eth_axis_tx.v
    lib/eth/rtl/udp_complete.v
    lib/eth/rtl/udp_checksum_gen.v
    lib/eth/rtl/udp.v
    lib/eth/rtl/udp_ip_rx.v
    lib/eth/rtl/udp_ip_tx.v
    lib/eth/rtl/ip_complete.v
    lib/eth/rtl/ip.v
    lib/eth/rtl/ip_eth_rx.v
    lib/eth/rtl/ip_eth_tx.v
    lib/eth/rtl/ip_arb_mux.v
    lib/eth/rtl/arp.v
    lib/eth/rtl/arp_cache.v
    lib/eth/rtl/arp_eth_rx.v
    lib/eth/rtl/arp_eth_tx.v
    lib/eth/rtl/eth_arb_mux.v
    lib/eth/lib/axis/rtl/arbiter.v
    lib/eth/lib/axis/rtl/priority_encoder.v
    lib/eth/lib/axis/rtl/axis_fifo.v
    lib/eth/lib/axis/rtl/axis_async_fifo.v
    lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
    lib/eth/lib/axis/rtl/sync_reset.v
} {
    read_verilog $ex/$s
}

# --- top + xdc ---
read_verilog $syn_dir/rtl/trace_probe_top.v
read_xdc     $syn_dir/constraints/trace_probe.xdc

synth_design -top trace_probe_top -part $part
puts "============ POST-SYNTH UTILIZATION ============"
report_utilization

opt_design
place_design
route_design

puts "============ POST-IMPLEMENTATION UTILIZATION ============"
report_utilization
puts "============ POST-IMPLEMENTATION TIMING ============"
report_timing_summary -no_detailed_paths -no_header
