# Stage-2 T4: full synthesis + implementation of trace_probe_top with real
# board pins and clock constraints, on xc7a35tfgg484-2.
#
# Goal: post-implementation utilization + timing slack — the authoritative
# answer to "does the trace probe fit on 35T?" Combines T1 (Ethernet),
# T2 (capture front-end), T3 (trace core) under one top.

set part xc7a35tfgg484-2
set syn_dir   [file dirname [info script]]
set repo_root [file normalize [file join $syn_dir .. ..]]
set veth      $repo_root/syn/external/verilog-ethernet
set ex        $veth/example/NexysVideo/fpga

# --- T2 capture front-end ---
read_verilog $syn_dir/rtl/trace_capture_a7.v
# --- T3 traceIF (hand-written Verilog) ---
read_verilog $repo_root/verilog/traceIF.v
# --- T3 Amaranth-derived modules (regenerated by export_trace_modules.py) ---
foreach m {tpiu_demux checksum_appender cobs_encoder super_framer} {
    read_verilog $syn_dir/$m.v
}
# --- T1 Ethernet stack (NexysVideo example) ---
foreach s {
    rtl/fpga_core.v
    rtl/debounce_switch.v
    rtl/sync_signal.v
    lib/eth/rtl/iddr.v
    lib/eth/rtl/oddr.v
    lib/eth/rtl/ssio_ddr_in.v
    lib/eth/rtl/ssio_ddr_out.v
    lib/eth/rtl/rgmii_phy_if.v
    lib/eth/rtl/eth_mac_1g_rgmii_fifo.v
    lib/eth/rtl/eth_mac_1g_rgmii.v
    lib/eth/rtl/eth_mac_1g.v
    lib/eth/rtl/axis_gmii_rx.v
    lib/eth/rtl/axis_gmii_tx.v
    lib/eth/rtl/lfsr.v
    lib/eth/rtl/eth_axis_rx.v
    lib/eth/rtl/eth_axis_tx.v
    lib/eth/rtl/udp_complete.v
    lib/eth/rtl/udp_checksum_gen.v
    lib/eth/rtl/udp.v
    lib/eth/rtl/udp_ip_rx.v
    lib/eth/rtl/udp_ip_tx.v
    lib/eth/rtl/ip_complete.v
    lib/eth/rtl/ip.v
    lib/eth/rtl/ip_eth_rx.v
    lib/eth/rtl/ip_eth_tx.v
    lib/eth/rtl/ip_arb_mux.v
    lib/eth/rtl/arp.v
    lib/eth/rtl/arp_cache.v
    lib/eth/rtl/arp_eth_rx.v
    lib/eth/rtl/arp_eth_tx.v
    lib/eth/rtl/eth_arb_mux.v
    lib/eth/lib/axis/rtl/arbiter.v
    lib/eth/lib/axis/rtl/priority_encoder.v
    lib/eth/lib/axis/rtl/axis_fifo.v
    lib/eth/lib/axis/rtl/axis_async_fifo.v
    lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
    lib/eth/lib/axis/rtl/sync_reset.v
} {
    read_verilog $ex/$s
}

# --- top + xdc ---
read_verilog $syn_dir/rtl/trace_probe_top.v
read_xdc     $syn_dir/constraints/trace_probe.xdc

synth_design -top trace_probe_top -part $part
puts "============ POST-SYNTH UTILIZATION ============"
report_utilization

opt_design
place_design
route_design

puts "============ POST-IMPLEMENTATION UTILIZATION ============"
report_utilization
puts "============ POST-IMPLEMENTATION TIMING ============"
report_timing_summary -no_detailed_paths -no_header

# r09 B1: dump worst-case slack for both setup and hold across all corners
# so the WNS/WHS numbers in the report are no longer ambiguous.
puts "============ WORST CASE SETUP / HOLD ============"
puts "--- worst SETUP path ---"
report_timing -delay_type max -max_paths 1 -path_type summary
puts "--- worst HOLD path ---"
report_timing -delay_type min -max_paths 1 -path_type summary
puts "--- IDDR-related hold paths (top 5) ---"
report_timing -delay_type min -max_paths 5 -path_type summary -through [get_pins -hierarchical -filter "REF_NAME == IDDR"]

# r09 A1 / r10 A1+NEW-3: prove the trace pipeline is in the routed netlist
# AND end-to-end connected (not just black-box shells). Cell counts + a
# real end-to-end timing path are the authoritative evidence.
puts "============ TRACE PIPELINE SURVIVAL CHECK ============"
foreach inst {u_capture u_traceif u_dmux u_chk u_cobs u_sf} {
    set cells [get_cells -quiet -hierarchical -filter "NAME =~ $inst/*"]
    if {[llength $cells] == 0} {
        set self [get_cells -quiet $inst]
        if {[llength $self] > 0} {
            set cells [get_cells -quiet -filter "PARENT == $inst"]
            if {[llength $cells] == 0} { set cells $self }
        }
    }
    set lut [llength [filter $cells "REF_NAME =~ LUT*"]]
    set ff  [llength [filter $cells "REF_NAME =~ FD*"]]
    set ram [llength [filter $cells "REF_NAME =~ RAMB*"]]
    set io  [llength [filter $cells "REF_NAME =~ IDDR* || REF_NAME =~ IDELAY*"]]
    puts [format "  %-12s : LUT=%4d FF=%4d BRAM=%2d IO=%2d  (%d total cells)" \
                 $inst $lut $ff $ram $io [llength $cells]]
}

# r10 A1: BRAM attribution (answer A2-Recheck — separate AsyncFIFO vs cobs)
puts "============ BRAM ATTRIBUTION ============"
puts "  AsyncFIFO RAMB: [llength [get_cells -quiet -hier -filter {REF_NAME =~ RAMB* && NAME =~ *u_frame_cdc*}]]"
puts "  cobs RAMB     : [llength [get_cells -quiet -hier -filter {REF_NAME =~ RAMB* && NAME =~ *u_cobs*}]]"

# r10 A1 + NEW-3: end-to-end timing path is the real connectivity proof.
puts "============ END-TO-END PIPELINE TIMING PATH ============"
report_timing -quiet \
    -from [get_pins -quiet -hier -filter {NAME =~ *u_traceif*construct_reg*/C}] \
    -to   [get_ports -quiet trace_dbg_data[*]] \
    -max_paths 3 -path_type summary -no_header

# r10 A3: false_path scope check.
puts "============ EXCEPTIONS SUMMARY (A3) ============"
report_exceptions -summary
puts "============ IDDR -> traceIF SAME-DOMAIN HOLD (A3) ============"
report_timing -quiet -delay_type min \
    -from [get_pins -quiet -hier -filter {NAME =~ *u_iddr*/Q1}] \
    -to   [get_pins -quiet -hier -filter {NAME =~ *u_traceif*/D}] \
    -max_paths 3 -path_type summary -no_header
